// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'clamped': string;
  'description': string;
  'details': string;
  'grid': string;
  'label': string;
  'toggle': string;
}
export const cssExports: CssExports;
export default cssExports;
